query($filterQuery: String!, $after: String, $pageSize: Int) { 
  search(
    type: REPOSITORY
    query: $filterQuery
    first: $pageSize
    after: $after
  ) {
    pageInfo {
      hasNextPage
      endCursor
    }
    repos: edges {
      repo: node {
        ... on Repository {
          owner {
            id
            login
            url
            avatarUrl
          }
          name
          url
          openIssues: issues(states: OPEN) {
            totalCount
          }
          stars: stargazers {
            totalCount
          }
        }
      }
    }
  }
}
